import { Vehicle } from '@showroom/types';

export interface CategorizedVehicle extends Vehicle {
  mainCategory: string;
  subCategory: string;
  modelPath?: string;
  acceleration0to60?: string;
  topSpeed?: string;
  downforce?: string;
  brakingDistance?: string;
  chassisType?: string;
  customHighlights?: string[];
}

export const MOCK_VEHICLES: CategorizedVehicle[] = [
  // 1. HYPERCARS & SUPERCARS (10 Cars with 10 3D Models)
  // Sub 1: Electric Track Specialists
  {
    id: 'h1',
    make: 'Veloce',
    model: 'Apex Evora Track Spec',
    year: 2026,
    price: 380000,
    mileage: 200,
    fuelType: 'Quad-Motor Electric',
    transmission: 'Single-Speed Direct',
    bodyStyle: 'Hypercar',
    color: 'Cyber Volt Yellow',
    engine: '1200 HP Quad Electric',
    horsepower: 1200,
    description: 'Track-focused electric hypercar with active downforce wings and carbon ceramic matrix brakes.',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Hypercars & Supercars',
    subCategory: 'Electric Track Specialists',
    modelPath: '/models/ferrari.glb',
    acceleration0to60: '1.95s',
    topSpeed: '255 mph',
    downforce: '780 kg @ 180 mph',
    brakingDistance: '92 ft (60-0 mph)',
    chassisType: 'T1000 Carbon Monocoque',
    customHighlights: ['Active Downforce Aero', '1200 HP Quad Vectoring', '350kW 800V Architecture'],
  },
  {
    id: 'h2',
    make: 'Apex',
    model: 'Kinetix GT Electric',
    year: 2025,
    price: 340000,
    mileage: 450,
    fuelType: 'Dual-Motor AWD',
    transmission: 'Direct Drive',
    bodyStyle: 'Hypercar',
    color: 'Stealth Matte Black',
    engine: '1050 HP Electric',
    horsepower: 1050,
    description: 'Lightweight carbon monocoque electric track weapon with 0-60 in 2.3 seconds.',
    images: ['https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Hypercars & Supercars',
    subCategory: 'Electric Track Specialists',
    modelPath: '/models/bugatti.glb',
    acceleration0to60: '2.10s',
    topSpeed: '242 mph',
    downforce: '640 kg @ 160 mph',
    brakingDistance: '96 ft (60-0 mph)',
    chassisType: 'Carbon-Titanium Hybrid Cell',
    customHighlights: ['Quad Torque Vectoring', 'Active Brake Cooling NACA', 'Active Aerodynamic Wing'],
  },
  {
    id: 'h7',
    make: 'Subaru',
    model: 'Apex BRZ Sub-Zero Sport',
    year: 2026,
    price: 215000,
    mileage: 100,
    fuelType: 'Boxer Twin-Turbo AWD',
    transmission: '6-Speed Manual Track',
    bodyStyle: 'Coupe',
    color: 'Sub-Zero Blue Pearl',
    engine: '2.5L Turbo Boxer-4',
    horsepower: 620,
    description: 'Special lightweight track-tuned boxer engine with active rear wing and forged alloy wheels.',
    images: ['https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Hypercars & Supercars',
    subCategory: 'Electric Track Specialists',
    modelPath: '/models/subaru.glb',
    acceleration0to60: '3.1s',
    topSpeed: '198 mph',
    downforce: '450 kg @ 140 mph',
    brakingDistance: '102 ft (60-0 mph)',
    chassisType: 'Reinforced Aluminum Spaceframe',
    customHighlights: ['Boxer Low-Center Gravity', 'Symmetrical AWD Torque Split', 'Track Spec Brake Ducting'],
  },

  // Sub 2: V12 Atmospheric Mechanical
  {
    id: 'h3',
    make: 'Kronos',
    model: 'Aero Berlinetta V12',
    year: 2026,
    price: 420000,
    mileage: 150,
    fuelType: 'V12 Naturally Aspirated',
    transmission: '7-Speed Sequential',
    bodyStyle: 'Coupe',
    color: 'Ignition Amber Metallic',
    engine: '6.5L V12',
    horsepower: 830,
    description: 'Pure mechanical revs up to 9,500 RPM with titanium exhaust manifold.',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Hypercars & Supercars',
    subCategory: 'V12 Atmospheric Mechanical',
    modelPath: '/models/aston.glb',
    acceleration0to60: '2.7s',
    topSpeed: '220 mph',
    downforce: '520 kg @ 160 mph',
    brakingDistance: '98 ft (60-0 mph)',
    chassisType: 'Carbon Fiber Monocoque',
    customHighlights: ['9500 RPM Redline', 'Inconel Exhaust Geometry', '7-Speed Sequential Box'],
  },
  {
    id: 'h4',
    make: 'Kronos',
    model: 'Spitfire V12 Corsa',
    year: 2025,
    price: 395000,
    mileage: 600,
    fuelType: 'V12 Gasoline',
    transmission: '6-Speed Manual Gated',
    bodyStyle: 'Coupe',
    color: 'Rosso Corsa Red',
    engine: '6.2L V12',
    horsepower: 790,
    description: 'Analog driving perfection with gated manual transmission and atmospheric V12 roar.',
    images: ['https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: false,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Hypercars & Supercars',
    subCategory: 'V12 Atmospheric Mechanical',
    modelPath: '/models/martin.glb',
    acceleration0to60: '2.9s',
    topSpeed: '215 mph',
    downforce: '480 kg @ 150 mph',
    brakingDistance: '100 ft (60-0 mph)',
    chassisType: 'Aluminum Carbon Composite',
    customHighlights: ['Gated 6-Speed Manual', 'Naturally Aspirated V12 Sound', 'Center-Lock Magnesium Wheels'],
  },
  {
    id: 'h8',
    make: 'Aston Martin',
    model: 'Aston Zagato Heritage Edition',
    year: 2026,
    price: 490000,
    mileage: 50,
    fuelType: 'V12 Twin-Turbo',
    transmission: '8-Speed Sportshift',
    bodyStyle: 'Coupe',
    color: 'Zagato Emerald Green',
    engine: '5.2L Twin-Turbo V12',
    horsepower: 860,
    description: 'Ultra-rare Zagato double-bubble roof styling with 860 HP twin-turbocharged V12 power.',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Hypercars & Supercars',
    subCategory: 'V12 Atmospheric Mechanical',
    modelPath: '/models/zagato.glb',
    acceleration0to60: '2.5s',
    topSpeed: '228 mph',
    downforce: '590 kg @ 170 mph',
    brakingDistance: '94 ft (60-0 mph)',
    chassisType: 'Hand-Hammered Carbon Aluminum Body',
    customHighlights: ['Zagato Double-Bubble Roof', 'Bespoke Bridge of Weir Leather', 'Titanium Quad Exhaust System'],
  },

  // Sub 3: V8 Twin-Turbo Hybrids & Armored Luxury
  {
    id: 'h5',
    make: 'Apex',
    model: 'Valiant V8 Hybrid GT',
    year: 2026,
    price: 290000,
    mileage: 300,
    fuelType: 'V8 Hybrid Twin-Turbo',
    transmission: '8-Speed Dual-Clutch',
    bodyStyle: 'Coupe',
    color: 'Cobalt Pearl Blue',
    engine: '4.0L V8 Hybrid',
    horsepower: 920,
    description: 'Twin-turbo V8 coupled with axial-flux electric torque vectoring.',
    images: ['https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Hypercars & Supercars',
    subCategory: 'V8 Twin-Turbo Hybrids',
    modelPath: '/models/carglb.glb',
    acceleration0to60: '2.4s',
    topSpeed: '235 mph',
    downforce: '610 kg @ 165 mph',
    brakingDistance: '95 ft (60-0 mph)',
    chassisType: 'T800 Carbon Tub',
    customHighlights: ['Axial Flux Motors', 'Active Aerodynamic Flaps', 'Carbon Ceramic Matrix Discs'],
  },
  {
    id: 'h9',
    make: 'Aurus',
    model: 'Aurus Komendant Armor SUV',
    year: 2026,
    price: 360000,
    mileage: 150,
    fuelType: 'V8 Twin-Turbo Hybrid',
    transmission: '9-Speed Automatic',
    bodyStyle: 'SUV',
    color: 'Imperial Black Metallic',
    engine: '4.4L V8 Twin-Turbo Hybrid',
    horsepower: 880,
    description: 'Executive VIP armored SUV with active air suspension and handcrafted interior.',
    images: ['https://images.unsplash.com/photo-1541348263662-e082662d82da?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Luxury SUVs',
    subCategory: 'Off-Road Armor Executives',
    modelPath: '/models/carglb.glb',
    acceleration0to60: '3.5s',
    topSpeed: '185 mph',
    downforce: '340 kg @ 130 mph',
    brakingDistance: '106 ft (60-0 mph)',
    chassisType: 'B7 Reinforced Heavy Armored Steel',
    customHighlights: ['Imperial B7 Security Suite', 'Massaging Executive Lounge', 'Active All-Wheel Air Suspension'],
  },
  {
    id: 'h10',
    make: 'Mercedes-Benz',
    model: 'S-Class W222 HQ Executive',
    year: 2026,
    price: 198000,
    mileage: 300,
    fuelType: 'V8 Biturbo Mild-Hybrid',
    transmission: '9-Speed 9G-Tronic',
    bodyStyle: 'Sedan',
    color: 'Obsidian Black Metallic',
    engine: '4.0L V8 Biturbo',
    horsepower: 612,
    description: 'Pinnacle luxury sedan featuring executive reclining rear seats and Burmester 4D Surround Sound.',
    images: ['https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Executive Sedans',
    subCategory: 'Plug-in Hybrid Limousines',
    modelPath: '/models/carglb.glb',
    acceleration0to60: '3.6s',
    topSpeed: '180 mph',
    downforce: '260 kg @ 130 mph',
    brakingDistance: '104 ft (60-0 mph)',
    chassisType: 'AIRMATIC Magic Body Control',
    customHighlights: ['Burmester 4D Audio', 'Active Multicontour Seats', 'ENERGIZING Comfort Control'],
  },
  {
    id: 'h11',
    make: 'Mercedes-Benz',
    model: 'G-Class 4x4 Squared Off-Road',
    year: 2026,
    price: 320000,
    mileage: 200,
    fuelType: 'V8 Biturbo',
    transmission: '9-Speed Automatic',
    bodyStyle: 'SUV',
    color: 'Monza Grey Magno',
    engine: '4.0L V8 Biturbo',
    horsepower: 585,
    description: 'Extreme off-road luxury beast with portal axles, carbon fiber wheel arches, and 18 inches ground clearance.',
    images: ['https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Luxury SUVs',
    subCategory: 'Off-Road Armor Executives',
    modelPath: '/models/carglb.glb',
    acceleration0to60: '4.5s',
    topSpeed: '130 mph',
    downforce: '200 kg @ 100 mph',
    brakingDistance: '118 ft (60-0 mph)',
    chassisType: 'Ladder Frame with Portal Axles',
    customHighlights: ['Portal Axles 18" Clearance', '3 Differential Locks', 'Carbon Fiber Body Kit'],
  },

  // 2. LUXURY SUVS & CONVERTIBLES
  {
    id: 's1',
    make: 'Apex',
    model: 'CyberSUV Ultra',
    year: 2026,
    price: 189000,
    mileage: 1200,
    fuelType: 'V8 Hybrid Twin-Turbo',
    transmission: '9-Speed Automatic',
    bodyStyle: 'SUV',
    color: 'Titanium Matte Gray',
    engine: '4.0L V8 Hybrid',
    horsepower: 850,
    description: 'Active predictive air suspension scans road surface 1000x per second.',
    images: ['https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Luxury SUVs',
    subCategory: 'Autonomous Air Suspensions',
    modelPath: '/models/carglb.glb',
    acceleration0to60: '3.2s',
    topSpeed: '190 mph',
    downforce: '320 kg @ 140 mph',
    brakingDistance: '105 ft (60-0 mph)',
    chassisType: 'Air-Suspended Aluminum Unibody',
    customHighlights: ['Laser Road Scanner', 'Executive Rear Reclining Seats', '420mm Carbon Ceramics'],
  },
  {
    id: 'g1',
    make: 'Veloce',
    model: 'Phantom Roadster GT',
    year: 2025,
    price: 245000,
    mileage: 850,
    fuelType: 'Electric High-Output',
    transmission: 'Single-Speed Direct',
    bodyStyle: 'Convertible',
    color: 'Midnight Carbon Sapphire',
    engine: 'Tri-Motor AWD',
    horsepower: 1020,
    description: 'Open-top electric hyper GT delivering instant 1020 HP torque vectoring.',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80'],
    status: 'AVAILABLE',
    featured: true,
    tenantId: 't1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mainCategory: 'Grand Tourer Convertibles',
    subCategory: 'Open-Top Electric GTs',
    modelPath: '/models/zagato.glb',
    acceleration0to60: '2.1s',
    topSpeed: '230 mph',
    downforce: '490 kg @ 150 mph',
    brakingDistance: '94 ft (60-0 mph)',
    chassisType: 'Carbon Fiber Monocoque Roadster',
    customHighlights: ['Open-Top Electric Thrill', 'Carbon Hardtop Roof', 'Active Air Scarf System'],
  },
];
